def chance(num_of_roll, the_sum, numerator):
    if num_of_roll == 1:
        return numerator + 0
    if num_of_roll == 2:
        if the_sum == 2:
            return numerator + 0
        if the_sum == 3:
            return numerator + 1
        if the_sum == 4:
            return numerator + 2
        if the_sum == 5:
            return numerator + 3
        if the_sum == 6:
            return numerator + 4
        if the_sum == 7:
            return numerator + 5
        if the_sum == 8:
            return numerator + 4
        if the_sum == 9:
            return numerator + 3
        if the_sum == 10:
            return numerator + 2
        if the_sum == 11:
            return numerator + 1
        if the_sum == 12:
            return numerator + 0
    if num_of_roll == 3:
        if the_sum == 3:
            return numerator + 0
        if the_sum == 4:
            return numerator + 2
        if the_sum == 5:
            return numerator + 5
        if the_sum == 6:
            return numerator + 9
        if the_sum == 7:
            return numerator + 14
        if the_sum == 8:
            return numerator + 20
        if the_sum == 9:
            return numerator + 24
        if the_sum == 10:
            return numerator + 26
        if the_sum == 11:
            return numerator + 26
        if the_sum == 12:
            return numerator + 24
        if the_sum == 13:
            return numerator + 20
        if the_sum == 14:
            return numerator + 14
        if the_sum == 15:
            return numerator + 9
        if the_sum == 16:
            return numerator + 5
        if the_sum == 17:
            return numerator + 2
        if the_sum == 18:
            return numerator + 0
    if num_of_roll == 4:
        if the_sum == 4:
            return numerator + 0
        if the_sum == 5:
            return numerator + 3
        if the_sum == 6:
            return numerator + 9
        if the_sum == 7:
            return numerator + 19
        if the_sum == 8:
            return numerator + 34
        if the_sum == 9:
            return numerator + 55
        if the_sum == 10:
            return numerator + 79
        if the_sum == 11:
            return numerator + 103
        if the_sum == 12:
            return numerator + 124
        if the_sum == 13:
            return numerator + 139
        if the_sum == 14:
            return numerator + 145
        if the_sum == 15:
            return numerator + 139
        if the_sum == 16:
            return numerator + 124
        if the_sum == 17:
            return numerator + 103
        if the_sum == 18:
            return numerator + 79
        if the_sum == 19:
            return numerator + 55
        if the_sum == 20:
            return numerator + 34
        if the_sum == 21:
            return numerator + 1
        if the_sum == 22:
            return numerator + 9
        if the_sum == 23:
            return numerator + 3
        if the_sum == 24:
            return numerator + 0
    if num_of_roll == 5:
        if the_sum == 5:
            return numerator + 0
        if the_sum == 6:
            return numerator + 4
        if the_sum == 7:
            return numerator + 14
        if the_sum == 8:
            return numerator + 34
        if the_sum == 9:
            return numerator + 69
        if the_sum == 10:
            return numerator + 125
        if the_sum == 11:
            return numerator + 205
        if the_sum == 12:
            return numerator + 304
        if the_sum == 13:
            return numerator + 419
        if the_sum == 14:
            return numerator + 539
        if the_sum == 15:
            return numerator + 650
        if the_sum == 16:
            return numerator + 734
        if the_sum == 17:
            return numerator + 779
        if the_sum == 18:
            return numerator + 779
        if the_sum == 19:
            return numerator + 734
        if the_sum == 20:
            return numerator + 650
        if the_sum == 21:
            return numerator + 539
        if the_sum == 22:
            return numerator + 419
        if the_sum == 23:
            return numerator + 304
        if the_sum == 24:
            return numerator + 205
        if the_sum == 25:
            return numerator + 125
        if the_sum == 26:
            return numerator + 69
        if the_sum == 27:
            return numerator + 34
        if the_sum == 28:
            return numerator + 14
        if the_sum == 29:
            return numerator + 4
        if the_sum == 30:
            return numerator + 0
